# Generated by Django 4.0.2 on 2023-04-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainCore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_address',
            new_name='email',
        ),
    ]
