# Generated by Django 4.0.2 on 2023-04-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCore', '0004_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
