# Generated by Django 4.0.2 on 2023-04-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainCore', '0005_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
