# Generated by Django 4.0.2 on 2023-05-14 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainCore', '0006_remove_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_name', models.CharField(max_length=300)),
                ('interest_rate', models.FloatField()),
                ('term', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_taking', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('credit_amount', models.FloatField()),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('borrowing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainCore.borrowing')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnScheme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('borrowing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainCore.borrowing')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('return_value', models.FloatField()),
                ('scheme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainCore.returnscheme')),
            ],
        ),
        migrations.CreateModel(
            name='JsonReimbursementScheme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme', models.TextField()),
                ('date', models.DateTimeField()),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditTaking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmation_date', models.DateTimeField()),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainCore.creditrequest')),
            ],
        ),
    ]
