# Generated by Django 4.0.2 on 2023-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCore', '0007_borrowing_creditrequest_returnscheme_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_consultant',
            field=models.BooleanField(default=False),
        ),
    ]
